### ISSUE TITLE
Running in JavaFX 8

### ISSUE THREAD

**Issue by jimbok8** [micycle1/ProcessingFX#1]
To get this to work in JDK JavaFX 8 I had to  change Main to:
```
public class Main {
    public static void main(String[] args) {
        //PApplet.main(MyPApplet.class);                
        com.sun.javafx.application.PlatformImpl.startup(new Runnable() {
		@Override
		public void run() {
                    try {
                        PApplet.main(MyPApplet.class);
                    } catch (Exception ex) {
                        Logger.getLogger(MyPApplet.class.getName()).log(Level.SEVERE, null, ex);
                    }
		}
	});                                
    }
}
```
and change part of MyPApplet to:
```
        try {
            //Application.launch(App.class);
            new App().start(new Stage());
        } catch (Exception ex) {
            Logger.getLogger(MyPApplet.class.getName()).log(Level.SEVERE, null, ex);
        }

```

But, thanks for this, much appreciated.
Jim

**Comment by FraDePace** [comment]
I tried the ProcessingFX project but I can't make it works.
I'm using :
**java 1.8.0_231
javaFX 8.0.231-b10**

If I run the project, I get the following error:
```
java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = main
	at com.sun.glass.ui.Application.checkEventThread(Application.java:443)
	at com.sun.glass.ui.Window.getScreen(Window.java:403)
	at com.sun.javafx.tk.quantum.WindowStage.setBounds(WindowStage.java:289)
	at javafx.stage.Window$TKBoundsConfigurator.apply(Window.java:1292)
	at javafx.stage.Window.applyBounds(Window.java:1182)
	at javafx.stage.Window.centerOnScreen(Window.java:283)
	at processing.javafx.PSurfaceFX.placeWindow(PSurfaceFX.java:564)
	at processing.core.PApplet.runSketch(PApplet.java:10849)
	at processing.core.PApplet.main(PApplet.java:10562)
	at processing.core.PApplet.main(PApplet.java:10534)
	at com.micycle.main.Main.main(Main.java:9)
```

If I apply your code @jimbok8 , I get the following error:
```
java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-2
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:444)
	at javafx.stage.Stage.<init>(Stage.java:241)
	at javafx.stage.Stage.<init>(Stage.java:227)
	at com.micycle.processing.MyPApplet$1.run(MyPApplet.java:35)
	at java.lang.Thread.run(Thread.java:748)
```

Any hints to solve this problem?
thank you :)

**Comment by jimbok8** [comment]
Can you post full code?

**Comment by FraDePace** [comment]
@jimbok8 solved :)
I was starting the Application class on the wrong thread.
Thank you
