### ISSUE TITLE
Error: java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = main

### ISSUE THREAD

**Issue by ylascer** [micycle1/ProcessingFX#7]
Oops!. I'd found the same issue at the "closed issue".  I'll try it's solution and comment.
--------------
I'm a newbie in Java, and very interested in your Project, so downloaded and imported to my latest eclipse(with JRE-SE-21) with JavaFX-SDK-22.
Having trouble at first time, but after applying 'VM arguments' on 'Run Configuration'
`--module-path "E:\JAVA프로그래밍\javafx-sdk-22.0.2\lib" --add-modules=javafx.controls,javafx.fxml,javafx.graphics --add-opens javafx.graphics/com.sun.javafx.geom=ALL-UNNAMED`
  (for information: and with JRE > Runtime JRE >  Project JRE (jre), )

I finally succeed to open main window.
but, PApplet canvas is not open, there are error message like below.
`java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = main
	at javafx.graphics@22.0.2/com.sun.glass.ui.Application.checkEventThread(Application.java:445)
	at javafx.graphics@22.0.2/com.sun.glass.ui.Window.getOwner(Window.java:342)
	at javafx.graphics@22.0.2/com.sun.glass.ui.win.WinWindow.notifyMoving(WinWindow.java:153)
	at javafx.graphics@22.0.2/com.sun.glass.ui.win.WinWindow.setBounds(WinWindow.java:125)
	at javafx.graphics@22.0.2/com.sun.javafx.tk.quantum.WindowStage.setBounds(WindowStage.java:320)
	at javafx.graphics@22.0.2/javafx.stage.Window$TKBoundsConfigurator.apply(Window.java:1572)
	at javafx.graphics@22.0.2/javafx.stage.Window.applyBounds(Window.java:1430)
	at javafx.graphics@22.0.2/javafx.stage.Window.centerOnScreen(Window.java:363)
	at processing.javafx.PSurfaceFX.placeWindow(PSurfaceFX.java:564)
	at processing.core.PApplet.runSketch(PApplet.java:10849)
	at processing.core.PApplet.main(PApplet.java:10562)
	at processing.core.PApplet.main(PApplet.java:10534)
	at com.micycle.main.Main.main(Main.java:11)`

Main.java:11 is
`PApplet.main(MyPApplet.class);`

And, if I click button or slide slider, there are many errors pops.

I had searched long time to solve this error, but failed.
What can I do for success? 

Below is the screenshot.  there does not show PApplet Sketch canvas on right anchorpane.
![image](https://github.com/user-attachments/assets/63d5f1a3-f9ec-43c5-a6b7-e7963ecf31e8)

**Comment by ylascer** [comment]
After applying martin-y-lu's solution at closed issue : https://github.com/micycle1/ProcessingFX/issues/4#issuecomment-596890503.  I finally succeed!!! 
Thank you very much. I'm very excited...
added code is like below
`public static void main(String[] args) { 
 System.setProperty("glass.disableThreadChecks", "true"); 
PApplet.main(MyPApplet.class); 
}`
